POST http://localhost:3000/visited 
Content-Type: application/json

{
    "xid": "444",
    "image": "url",
    "name": "Leaning Tower",
    "city": "Ózd",
    "countryCode": "444",
    "kinds": "architecture, heritage",
    "rating": 10,
    "listType": "visited"
}

###

DELETE http://localhost:3000/visited/3

###

GET http://localhost:3000/visited
