POST http://localhost:3000/visited 
Content-Type: application/json

{
    "xid": "666",
    "image": "url",
    "name": "Hell",
    "city": "Budapest",
    "countryCode": "444",
    "kinds": "architecture, heritage",
    "rating": 10,
    "listType": "wished"
}

###

DELETE http://localhost:3000/visited/3

###

GET http://localhost:3000/visited


###
GET http://localhost:3000/visited 
